name: pytester

on:
    workflow_dispatch: {}

    pull_request:
      branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.10"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install pytest pytest-md pytest-emoji clickhouse_connect python-dotenv
            - name: Create env file
              run: |
                  echo "${{ secrets.ENV_FILE }}" > .env
            - name: Test with pytest
              run: |
                python -m pytest tests
              env:
                CLICKHOUSE_HOST: ${{ secrets.CLICKHOUSE_HOST }}
                CLICKHOUSE_PORT: ${{ secrets.CLICKHOUSE_PORT }}
                CLICKHOUSE_USERNAME: ${{ secrets.CLICKHOUSE_USERNAME }}
                CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
